### ISSUE TITLE
Unify all the labels bg color

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/explorer-ui#94]
We are using very different and very bright colors for each label in the process: "Autostart" "Weighted" etc. making it difficult to read and with a funny look. 

Unify all the labels colors to: rgb(35, 114, 116)

![image](https://user-images.githubusercontent.com/6894329/227565397-25c1fb85-74ba-498d-ada1-eaa46dd29401.png)

**Comment by selankon** [comment]
I am not sure of change the color of the process status badge (on above image the `upcoming` badge), because on the process lists cards they have a specific color depending of the status. This is how it looks like 

![image](https://user-images.githubusercontent.com/16777076/229485536-437f4c7d-cc8f-4b08-9e6f-39512662f9fa.png)

**Comment by jpaulet** [comment]
Solved with the new issue #108

**Comment by selankon** [comment]
https://github.com/vocdoni/explorer-ui/pull/110
